name: Create Tag on package.json update

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: "${{ secrets.GH_AUTH_TOKEN }}"
          fetch-depth: 0
      - uses: butlerlogic/action-autotag@2.1.1
        with:
          GITHUB_TOKEN: "${{ secrets.GH_AUTH_TOKEN }}"
          tag_prefix: "v"
